# Generated by Django 4.0.2 on 2024-03-21 17:19

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=12)),
                ('email', models.BooleanField(default=True)),
                ('submitted_date', models.DateField()),
                ('submitted_time', models.TimeField()),
                ('submitted_date_time', models.DateTimeField()),
                ('photo', models.FileField(blank=True, null=True, upload_to='protected_files/contact_forms/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
            ],
            options={
                'verbose_name_plural': 'Contact Forms',
                'ordering': ('-created_at',),
            },
        ),
    ]
