# Generated by Django 4.0.2 on 2024-05-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_websubscriber_alter_contactform_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websubscriber',
            name='email',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
