# Generated by Django 4.2.13 on 2024-06-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_websubscriber_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='submitted_date',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='submitted_date_time',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='submitted_time',
        ),
        migrations.AddField(
            model_name='contactform',
            name='first_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='contactform',
            name='last_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='contactform',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contactform',
            name='subject',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.CharField(default='', max_length=256),
        ),
    ]
