# Generated by Django 4.2.13 on 2024-06-22 19:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_remove_contactform_name_remove_contactform_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=2048, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('excerpt', models.CharField(blank=True, max_length=2048, null=True)),
                ('preview_photo', models.FileField(blank=True, null=True, upload_to='blogs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('preview_photo_from_url', models.CharField(blank=True, max_length=2048, null=True)),
                ('slug', models.SlugField(blank=True, max_length=2048, unique=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_writer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blogs',
                'ordering': ('-created_at', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=2048, unique=True)),
                ('label_type', models.CharField(choices=[('TAG', 'TAG'), ('CATEGORY', 'CATEGORY')], max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Labels',
                'ordering': ('title', 'label_type'),
            },
        ),
        migrations.CreateModel(
            name='BlogLabel',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_label_blog', to='app.blog')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_label_label', to='app.label')),
            ],
            options={
                'verbose_name_plural': 'Blog Labels',
                'ordering': ('-created_at',),
            },
        ),
    ]
